'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class frmAsignaCategoriasSAC

    '''<summary>
    '''lbl_año_vigencia control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_año_vigencia As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txt_año_vigencia control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_año_vigencia As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lbl_version_enmienda control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_version_enmienda As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txt_version_enmienda control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_version_enmienda As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lbl_periodo_enmienda_sac control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_periodo_enmienda_sac As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txt_periodo_año_inicial control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_periodo_año_inicial As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lbl_al control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_al As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txt_periodo_año_final control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_periodo_año_final As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lbl_nombre_insrumento control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_nombre_insrumento As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txt_nombre_instrumento control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_nombre_instrumento As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lbl_categoria_asignar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_categoria_asignar As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddl_categoria_asignar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddl_categoria_asignar As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''lbl_codigo_arancel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_codigo_arancel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txt_codigo_arancel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_codigo_arancel As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btn_seleccionar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_seleccionar As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Datos_SAC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Datos_SAC As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''lbl_descripcion_capitulo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_descripcion_capitulo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txt_descripcion_capitulo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_descripcion_capitulo As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lbl_descripcion_partida control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_descripcion_partida As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txt_descripcion_partida control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_descripcion_partida As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lbl_descripcion_sub_partida control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_descripcion_sub_partida As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txt_descripcion_sub_partida control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_descripcion_sub_partida As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Datos_GridView control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Datos_GridView As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''gvAsignarCategorias control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvAsignarCategorias As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''btn_asigna_categoria control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_asigna_categoria As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btn_Salir control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_Salir As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''hfIdInstrumento control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfIdInstrumento As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hfCheckInciso control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfCheckInciso As Global.System.Web.UI.WebControls.HiddenField
End Class
